//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_B_Dnevnik_ishrane
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dnevnik_ishrane_db_Entities : DbContext
    {
        public dnevnik_ishrane_db_Entities()
            : base("name=dnevnik_ishrane_db_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kandidat> kandidats { get; set; }
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<mjerenje> mjerenjes { get; set; }
        public virtual DbSet<namirnica> namirnicas { get; set; }
        public virtual DbSet<obrok> obroks { get; set; }
        public virtual DbSet<plan_ishrane> plan_ishrane { get; set; }
        public virtual DbSet<plan_vjezbanja> plan_vjezbanja { get; set; }
        public virtual DbSet<trener> treners { get; set; }
    }
}
