//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_B_Dnevnik_ishrane
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        public int idKORISNIK { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public int Godiste { get; set; }
        public string Tema { get; set; }
    
        public virtual kandidat kandidat { get; set; }
        public virtual trener trener { get; set; }
    }
}
