//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_B_Dnevnik_ishrane
{
    using System;
    using System.Collections.Generic;
    
    public partial class namirnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public namirnica()
        {
            this.obroks = new HashSet<obrok>();
        }
    
        public int idNAMIRNICA { get; set; }
        public string Naziv { get; set; }
        public decimal Kolicina { get; set; }
        public decimal KalorijskaVrijednost { get; set; }
        public decimal Proteini { get; set; }
        public decimal Masti { get; set; }
        public decimal UgljikoHidrati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<obrok> obroks { get; set; }
    }
}
