//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_B_Dnevnik_ishrane
{
    using System;
    using System.Collections.Generic;
    
    public partial class obrok
    {
        public int KANDIDAT_KORISNIK_idKORISNIK { get; set; }
        public int NAMIRNICA_idNAMIRNICA { get; set; }
        public decimal Kolicina { get; set; }
        public string TipObroka { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual kandidat kandidat { get; set; }
        public virtual namirnica namirnica { get; set; }
    }
}
