//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_B_Dnevnik_ishrane
{
    using System;
    using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations.Schema;

  public partial class plan_ishrane
    {
    public int idPLAN_ISHRANE { get; set; }
        public System.DateTime DatumVrijeme { get; set; }
        public string Opis { get; set; }
        public int TRENER_KORISNIK_idKORISNIK { get; set; }
        public int KANDIDAT_KORISNIK_idKORISNIK { get; set; }
        public string Dan { get; set; }
    
        public virtual kandidat kandidat { get; set; }
        public virtual trener trener { get; set; }
    }
}
